version: '3.7'

services:
  sale-realtime-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: db
    container_name: 'sale-realtime-api'
    restart: 'always' #on-failure
    #expose:
    #  - '14000'
    #ports:
    #  - '14000:14000'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - api_network
      - postgres_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.salerealtime.entrypoints=salerealtime"
      - "traefik.http.routers.salerealtime.rule=PathPrefix(`/`)"
      - "traefik.http.routers.salerealtime.service=sale-realtime-api"
      - "traefik.http.services.sale-realtime-api.loadbalancer.server.port=14000"
      - "traefik.docker.network=api_network"
# Networks to be created to facilitate communication between containers
networks:
  postgres_network:
    external: true
  api_network:
    external: true

#services:
#  mfg-4b-sz:
    #build:
    #  context: .
    #  labels:
    #    - "com.minor.description=Sizzler webapp"
    #    - "com.minor.department=FoodIT"
    #  target: prod
    #deploy:
    #  mode: replicated = * / global=1
    #  replicas: 1
    #  endpoint_mode: dnsrr
    #  labels:
    #        com.example.description: "This label will appear on the web service"
    #  placement:
    #    constraints:
    #      - node.role == manager
    #      - engine.labels.operatingsystem == ubuntu 14.04
    #    preferences:
    #      - spread: node.labels.zone
    #  resources:
    #    limits:
    #      cpus: '0.50'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M
    #  restart_policy: #Out of memory exception
    #    condition: on-failure
    #    delay: 5s
    #    max_attempts: 3
    #    window: 120s
    #logging:
    #  driver: "json-file"
    #  options:
    #    max-size: "200k"
    #    max-file: "10"
    #network_mode: "bridge"
    #networks:
    #  - some-network
    #  - other-network
    #port:port #HOST:CONTAINER
#devices:
#  - "/dev/ttyUSB0:/dev/ttyUSB0"
#dns: 8.8.8.8
#entrypoint:
#  - /code/entrypoint.sh
#env_file:
#  - ./common.env
#  - ./apps/web.env
#environment:
#  - RACK_ENV=development
#  - SHOW=true
#  - SESSION_SECRET
#extra_hosts:
#  - "somehost:162.242.195.82"
#  - "otherhost:50.31.209.229"
#healthcheck:
#  test: ["CMD", "curl", "-f", "http://localhost"]
#  interval: 1m30s
#  timeout: 10s
#  retries: 3
#  start_period: 40s
